site_name: Blogs for Leepi (à¤²à¤¿à¤ªà¤¿)
copyright: Copyright &copy; 2022 Leepi

nav:
  - ğŸ  Home:
    - index.md
  - ğŸ§¬ Tech:
    - tech/index.md
    - Hand Sign Classifiers : tech/classifiers/index.md
    - Hand Detectors : tech/detectors/index.md
  - ğŸˆ Privacy Policy:
    - policy/index.md
    
  - â˜€ï¸ Ekatra:
    - ekatra/index.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/leepiapp
      name: Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/princep
      name: Github
  version:
    default: stable
    provider: mike
  alternate:
    - name: English
      link: /en/
      lang: en

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
  - navigation.indexes
  - navigation.tabs
  - search.highlight
  - search.share
  - content.code.annotate
  - content.tabs.link

  palette:
    primary: indigo
  font:
    text: Open Sans
    code: Noto Sans
  